export const ROUTES = {
  home:               '/',
  login:              '/login',
  acceptInvite:       '/accept-invite',
  forgotPassword:     '/forgot-password',
  resetPassword:      '/reset-password',
  dashboard:          '/dashboard',
  organisation:       '/organisation',
  clinics:            '/clinics',
  clinic:             (id: string) => `/clinics/${id}`,
  patients:           '/patients',
  patient:            (id: string) => `/patients/${id}`,
  enrollment:         (patientId: string, enrollmentId: string) => `/patients/${patientId}/enrollments/${enrollmentId}`,
  myChildren:         '/my-children',
  calendar:           '/calendar',
  availability:       '/availability',
  inquiries:          '/inquiries',
  tasks:              '/tasks',
  feed:               '/feed',
  workforce:          '/workforce',
  /** Deep-link a Workforce tab, e.g. workforceTab('leave-requests') */
  workforceTab:       (tab: string) => `/workforce?tab=${tab}`,
  members:            '/members',
  member:             (id: string) => `/members/${id}`,
  analytics:          '/analytics',
  activities:         '/activities',
  activity:           (id: string) => `/activities/${id}`,
  createActivity:     '/activities/new',
  editActivity:       (id: string) => `/activities/${id}/edit`,
} as const
