export const ROUTES = {
  home:               '/',
  login:              '/login',
  acceptInvite:       '/accept-invite',
  forgotPassword:     '/forgot-password',
  resetPassword:      '/reset-password',
  dashboard:          '/dashboard',
  organisation:       '/organisation',
  clinics:            '/clinics',
  clinic:             (id: string) => `/clinics/${id}`,
  patients:           '/patients',
  patient:            (id: string) => `/patients/${id}`,
  myChildren:         '/my-children',
  calendar:           '/calendar',
  availability:       '/availability',
  inquiries:          '/inquiries',
  tasks:              '/tasks',
  workforce:          '/workforce',
  members:            '/members',
  analytics:          '/analytics',
  attendance:         '/attendance',
  leaveManagement:    '/leave-management',
  attendanceManagement: '/attendance-management',
} as const
